### ISSUE TITLE
Exception when trying to view a Dicom file

### ISSUE THREAD

**Issue by ayoubmtd** [slicebox/slicebox#58]
Hello, I am trying to use Slicebox and I imported a DICOM and it was accepted. but I try to visualize the image I get an exception. 
Here is the call stack.
```

2016-02-23 16:06:15,644 ERROR akka.actor.RepointableActorRef - Error during processing of request HttpRequest(GET,http://localhost:5000/api/images/33/png?framenumber=1&imageheight=0,List(Remote-Address: 127.0.0.1, Host: localhost:5000, User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0, Accept-Language: en-US, en;q=0.5, Accept-Encoding: gzip, deflate, Referer: http://localhost:5000/, Cookie: slicebox-session=977e9049-2049-4524-97e8-7500f9ef4e5a, Connection: keep-alive),Empty,HTTP/1.1)
javax.imageio.IIOException: Unsupported JPEG process: SOF type 0xc3
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method) ~[na:1.8.0_66-internal]
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:609) ~[na:1.8.0_66-internal]
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:347) ~[na:1.8.0_66-internal]
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.gotoImage(JPEGImageReader.java:481) ~[na:1.8.0_66-internal]
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:602) ~[na:1.8.0_66-internal]
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1059) ~[na:1.8.0_66-internal]
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039) ~[na:1.8.0_66-internal]
	at javax.imageio.ImageIO.read(ImageIO.java:1448) ~[na:1.8.0_66-internal]
	at javax.imageio.ImageIO.read(ImageIO.java:1352) ~[na:1.8.0_66-internal]
	at se.nimsa.sbx.storage.StorageServiceActor$$anonfun$readSecondaryCaptureJpeg$1$$anonfun$apply$17.apply(StorageServiceActor.scala:311) ~[classes/:na]
	at se.nimsa.sbx.storage.StorageServiceActor$$anonfun$readSecondaryCaptureJpeg$1$$anonfun$apply$17.apply(StorageServiceActor.scala:301) ~[classes/:na]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:1.0.0-M1]
	at se.nimsa.sbx.storage.StorageServiceActor$$anonfun$readSecondaryCaptureJpeg$1.apply(StorageServiceActor.scala:301) ~[classes/:na]
	at se.nimsa.sbx.storage.StorageServiceActor$$anonfun$readSecondaryCaptureJpeg$1.apply(StorageServiceActor.scala:300) ~[classes/:na]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) ~[scala-library-2.11.6.jar:1.0.0-M1]
	at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.6.jar:1.0.0-M1]
	at scala.util.Success.map(Try.scala:236) ~[scala-library-2.11.6.jar:1.0.0-M1]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library-2.11.6.jar:na]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[na:1.8.0_66-internal]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_66-internal]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_66-internal]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_66-internal]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_66-internal]

```

How Can I fix this exception ?

**Comment by KarlSjostrand** [comment]
It looks like the image you are trying to view is encapsulated lossless jpeg. Slicebox is not shipped with a decoder for this format (perhaps we should consider this). You can try installing a decoder through e.g. Java Advanced Imaging. If you can live without viewing this particular type of file you can still use Slicebox for storing, organizing and transmitting these files, and leave viewing to third party clients.
